### ISSUE TITLE
Отрефакторить тесты так, чтобы работала валидация.

### ISSUE THREAD

**Issue by IgorMaksymov** [JuniorsJava/itevents#111]
1. Реализовать AbstractWebTest только с веб-контекстом (без БД) - **неактуально**
2. Сделать для примера тесты 2-х контроллеров наследуясь от AbstractWebTest - **неактуально**
3. Добавить валидацию входящих параметров и добиться ее правильной работы (достаточно 1-го рабочего пример

**Comment by IgorMaksymov** [comment]
blocked with #134 @AndriyBaibak @vaa25

**Comment by vkuchyn** [comment]
@IgorMaksymov returned ticket to to store issue history
