### ISSUE TITLE
Пофіксити тести

### ISSUE THREAD

**Issue by zccmj** [JuniorsJava/itevents#117]
Якщо запустити послідовно `RoleMapperDbTest` далі `UserMapperDbTest` далі `CityMapperDbTest`, то останій тест і всі за ним будуть фейлитись.

**Comment by vaa25** [comment]
там нужно правильно расставить DatabaseSetup и DatabaseTeardown

**Comment by alex-anakin** [comment]
На будущее, если заводите таску с пометкой BUG, добавляйте коммент со стектрейсом ошибок
