### ISSUE TITLE
Прибрати пароль який повертається після виклику методу users/me

### ISSUE THREAD

**Issue by vkuchyn** [JuniorsJava/itevents#129]
1. Після виклику методу users/me у відповіді надсилається пароль. Це порушення правил безпеки - необхідно його вилучити звідти.
2. Перевірити решту рест методів, які повертають інформацію користувача, чи не містять вони пароль

**Comment by IgorMaksymov** [comment]
та же ошибка может быть в други методах, где есть отсылка к мапперу гетЮзер, он возвращает юзера целиком в т.ч. поле с паролем.

**Comment by zccmj** [comment]
Так, це повинно фікситись доволі просто додавши в поле юзера  `@JsonIgnore`

**Comment by IgorMaksymov** [comment]
подожди, мы же все равно берем из базы пароль и передаем его в ответе.
Я бы убрал его в маппере т.к. это поле знать обьекту Юзер совершенно незачем

**Comment by zccmj** [comment]
Навіщо ускладнювати, просто не будемо його передавати у відповіді, а в моделі він потрібен для реалізації security

**Comment by IgorMaksymov** [comment]
точно нуджен в секурити?
ибо в том что реализовано сейчас в мастере, я вижу что он просто берет поле пароль из базы, а не из обьекта.
т.е. базу паролей вообще можно вынести в отдельную таблицу юзерИД-пароль

**Comment by vkuchyn** [comment]
Обидва озвучені підходи і правильні і ні одночасно :)
1. @JsonIgnore чим поганий. Напр, формат поміняється на xml, або взагалі інтерфейс будуватиметься не на http. Тоді аннотація втратить смисл
2. Дійсно, можно рознести методи для секюріті щось типу boolean checkUserPassword(login, password). Це створить додаткове навантаження на бд і необхідність підтримувати додатковий метод. А в моделі  UserInfo getUserInfo(login) вилучити поля пароль. 
Та цей підхід реалізує принцип Single responsibility - один метод має своє призначення.

**Comment by IgorMaksymov** [comment]
blockerd with #138 @AndriyBaibak
