### ISSUE TITLE
Повертати json якщо ресурс вимагає авторизації

### ISSUE THREAD

**Issue by vkuchyn** [JuniorsJava/itevents#130]
У випадку, коли ресурс вимагає авторизації (напр users/me), а користувач не авторизований необхідно повертати статус код 401 + json з тегом помилки і описом помилки
Зараз повертається HTML сторінка

**Comment by vaa25** [comment]
а возврат 401 со страницей сформированной jetty подойдет?

**Comment by romach** [comment]
@AndriyBaibak time tracking: 1 hour spent

**Comment by romach** [comment]
@AndriyBaibak time tracking: 2 hours spent

**Comment by romach** [comment]
@AndriyBaibak time tracking: 1 hour spent

**Comment by romach** [comment]
This bug is not actual. It was fixed in #197
