### ISSUE TITLE
Пофиксить тест UserMapperDbTest.shouldAddUser() для issue129

### ISSUE THREAD

**Issue by IgorMaksymov** [JuniorsJava/itevents#138]
Выдает такую ошибку:
`org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.executor.ExecutorException: Error getting generated key or setting result to parameter object. Cause: org.apache.ibatis.binding.BindingException: Parameter 'id' not found. Available parameters are [password, user, param1, param2]`

Проблема в маппере
`org.itevents.dao.mybatis.mapper.UserMapper#addUser`
не удается получить поле `Role.id`
если передавать только 1 параметр в маппер(`@Param` или вообще без аннотации) то Майбатис получает значение нормально.

**Comment by vaa25** [comment]
Problem solved in issue #134

**Comment by vkuchyn** [comment]
@vaa25 should @AndriyBaibak close this issue as duplicate?

**Comment by vaa25** [comment]
@vkuchyn I fixed this bug in #134 that already in master, but @IgorMaksymov reopened it. I guess he broked this test again. Maybe he failed merge with master, I didn't penetrate.

**Comment by vkuchyn** [comment]
@IgorMaksymov Is there some reason for reopen?

**Comment by IgorMaksymov** [comment]
@vkuchyn i remembered that you are closing issues.

**Comment by vkuchyn** [comment]
@IgorMaksymov I see. So, next time - leave a comment please - @<username> pls close this issue
