### ISSUE TITLE
Додати тестовий REST Html клієнт для REST service

### ISSUE THREAD

**Issue by vkuchyn** [JuniorsJava/itevents#14]
https://github.com/swagger-api/swagger-codegen
Клієнт, який на основі yaml файлу генерує HTML REST клієнт. 
Додати gradle task для генерації yaml файлу опису проекту. Це можно зробити з   wadl файлу, який в свою чергу може автоматично згенерувати Spring MVC 
http://javattitude.com/2014/05/26/wadl-generator-for-spring-rest/

**Comment by IgorMaksymov** [comment]
branch itev-14
