### ISSUE TITLE
fix test shouldGrantAccessToRegisterNewSubscriberForAnonymous

### ISSUE THREAD

**Issue by IgorMaksymov** [JuniorsJava/itevents#151]
Когда тест запускается в одиночку, а не вместе с классом целиком, он падает с ошибкой java.lang.AssertionError: Authentication should not be null

http://pastebin.com/RGmszact

**Comment by vaa25** [comment]
@IgorMaksymov where is this test placed?

**Comment by IgorMaksymov** [comment]
@vaa25 we have only one test with such name
org.itevents.integration.SecurityTests#shouldGrantAccessToRegisterNewSubscriberForAnonymous

**Comment by IgorMaksymov** [comment]
@AndriyBaibak this task is not actual, bug is not repeating
