### ISSUE TITLE
Default properties

### ISSUE THREAD

**Issue by vaa25** [JuniorsJava/itevents#152]
Add global.properties as says at [meeting](https://github.com/JuniorsJava/itevents/wiki/%D0%A0%D0%B5%D0%B7%D1%8E%D0%BC%D0%B5-%D0%B7%D1%83%D1%81%D1%82%D1%80%D1%96%D1%87%D1%96-24.09.15)
`Треба створити налаштування, які б завантажувались за відсутності local.properties`

**Comment by vkuchyn** [comment]
@vaa25 assigned to you to store history
