### ISSUE TITLE
fix ignored tests in branch #48-otp

### ISSUE THREAD

**Issue by IgorMaksymov** [JuniorsJava/itevents#155]
fix this tests for brach  #48-otp:
1) `org.itevents.service.transactional.MyBatisUserServiceTest#shouldThrowEntityAlreadyExistsServiceExceptionWhenAddExistingSubscriber`

2)`public void shouldSendEmailWithActivationLink() throws Exception`(deleted (04 march 16) on request for @IgorMaksymov )

3) `org.itevents.service.transactional.MyBatisUserServiceTest#shouldAddSubscriber`

**Comment by romach** [comment]
@AndriyBaibak time tracking: 1 hour spent

**Comment by romach** [comment]
blocked with #156 @AndriyBaibak @Garazd pls fix it ASAP

**Comment by romach** [comment]
@AndriyBaibak time tracking: 30 minutes spent

**Comment by IgorMaksymov** [comment]
@AndriyBaibak please, make 2-nd task inactual here, because it is actual in issue #155

**Comment by AndriyBaibak** [comment]
@IgorMaksymov @romach update task
