### ISSUE TITLE
Не работает функция "Я пойду"

### ISSUE THREAD

**Issue by vaa25** [JuniorsJava/itevents#160]
При запуске в сваггере  /events/-5/assign сваггер возвращает :
400
Try to get event id=-5 with date Fri Jul 05 00:00:00 EEST 2115 as future event

**Comment by IgorMaksymov** [comment]
why unit-tests not cought this?

**Comment by vaa25** [comment]
@IgorMaksymov because its absent

**Comment by IgorMaksymov** [comment]
@vaa25 why its absent? i there was lots of tests for this feature.

**Comment by vaa25** [comment]
@IgorMaksymov Because real problem is in other feature, and that tests are absent

**Comment by IgorMaksymov** [comment]
@vaa25 it is so hard to explain this in first comment? From your message, i understood that it was my fault that i missed some unit-test when i was writing assign feature

**Comment by vaa25** [comment]
@IgorMaksymov no, not yours

**Comment by vaa25** [comment]
@AndriyBaibak 15 min effective time, 1 hour total

**Comment by vkuchyn** [comment]
@vaa25 returned this ticket for you to store issue history
