### ISSUE TITLE
You can re-register your mail by changing case

### ISSUE THREAD

**Issue by Garazd** [JuniorsJava/itevents#164]
You can register multiple accounts by changing case in email. For example: email@gmail.com and Email@gmail.com perceived as a different mail in database.

**Comment by IgorMaksymov** [comment]
blocked with #155 @AndriyBaibak @romach

**Comment by IgorMaksymov** [comment]
@AndriyBaibak time spent: 10m

**Comment by IgorMaksymov** [comment]
@AndriyBaibak time spent: 3h

**Comment by vaa25** [comment]
@Garazd @IgorMaksymov @AndriyBaibak @alex-anakin According to [Wikipedia](https://en.wikipedia.org/wiki/Email_address#Local_part)  email@gmail.com and Email@gmail.com are different emails. As I understood, case insensitive only part of address after `@`. So I propose to clarify the wording of this issue.
