### ISSUE TITLE
Process crawler technical requrements and make architecture decision

### ISSUE THREAD

**Issue by vkuchyn** [JuniorsJava/itevents#169]
https://docs.google.com/document/d/1RJG4Dg35DgT-6HLjLTmGrawzI3U2Kq6HBgESA2mtX_A/edit#
Process this document. Make sure - it is clear for you. You are welcome to ask questions in comments to google doc. 
As result of this issue must be architecture decision posted to another google doc - so we can discuss it.

**Comment by vaa25** [comment]
@vkuchyn [Doc](https://docs.google.com/document/d/1VUIU-DV1VQls2V6Yt3IrrOMexkalaP1__-8z1r-wLlA/edit?usp=sharing).

**Comment by vkuchyn** [comment]
@vaa25 thanks, will review soon.

**Comment by vkuchyn** [comment]
@vaa25 see my comments and process them. Need minor improvement

**Comment by vaa25** [comment]
@vkuchyn answered to you there

**Comment by vkuchyn** [comment]
@vaa25 shall I review again? It is not clear with uniq key for event - only problem declaration

**Comment by vaa25** [comment]
@AndriyBaibak 4 hours

**Comment by vkuchyn** [comment]
@vaa25 nice job. thanks!
