### ISSUE TITLE
Фільтр подій:

### ISSUE THREAD

**Issue by vkuchyn** [JuniorsJava/itevents#17]
Додати функціональність фільтрування подій до існуючого методу перегляд списку подій. 
URL Буде виглядати наступним чином: http://host/itevents?radius=10&cityId=23&lat=50.434&lon=30.543&payed=true&techTag=java&techTag=javascript

cityId - ідентифікатор міста. Для спрощення пошуку, ми будемо тримати словник з найпопулярнішими містами і їх координатами. Якщо вказано і місто і радіус з координатами - місто в більшому приоритеті.
radius - радіус в метрах
lat, lon - координати latitude, longitude відповідно
payed - платні, безкоштовні
techTag - тег технології. Їх може бути декілька. Якщо декілька, то у виборці БД логічна умова OR

**Comment by vaa25** [comment]
не понятно взаимодействие следующих параметров: radius, cityId, lat, lon
payed и list<techTag> нужно добавить в таблицу events?

**Comment by zccmj** [comment]
В PostGis є функції які роблять виборку наприклад `SELECT ST_X(coords), ST_Y(coords) FROM  events;`

**Comment by alex-anakin** [comment]
@vaa25 
словник з найпопулярнішими містами і їх координатами - это отдельная таблица
все параметры задаются пользователем в запросе,

**Comment by vaa25** [comment]
Як User я хочу фільтрувати події по технологіям, містом проведенням, радіусом, платності або безкоштовності (user_filter_events)

Значит подии должны содержать еще и информацию о технологиях и платности. В Events? А еще Виктор говорил что-то о валюте. Events сейчас содержат координаты. Будет также таблица с городами и их координатами. Каким образом осуществлять привязку подии к городу, чтобы потом можно было найти подию по городу?

**Comment by vkuchyn** [comment]
[8/1/15, 10:18:06 AM] Viktor Kuchyn: У нас 2 варіанти:
1. По місту. Кожна подія мапиться на якесь місто на момент грабінгу
2. По координатам. Тут - центр + радіус

Місто має більший приоритет. Якщо Ми вибрали Київ, то радіус і центр (координати) ігноруються в запиті.
