### ISSUE TITLE
Create brief description of crawler module

### ISSUE THREAD

**Issue by vkuchyn** [JuniorsJava/itevents#170]
Add brief description below technical decisions in [Обсуждение архитектуры краулера](https://docs.google.com/document/d/1VUIU-DV1VQls2V6Yt3IrrOMexkalaP1__-8z1r-wLlA/edit).
Add 1-2 schema of modules relation, describe each module. Should be sound like next
_Module should be Java application with main method run by cron. Contains at least 2 modules - Engine, Integration. 
Responsibilities:
Engine: 
- run integrations, process event with business logic rules. 
- process geo coordinates
- etc.

Integration:
- grab event from eternal source
- generate unique id
-etc._

Don't forget to mention DAO from ITevents.
This will be technical decision enough to start development.

UPD: also, list main technologies and frameworks

**Comment by vaa25** [comment]
@vkuchyn [Doc](https://docs.google.com/document/d/1VUIU-DV1VQls2V6Yt3IrrOMexkalaP1__-8z1r-wLlA/edit)

**Comment by vaa25** [comment]
@AndriyBaibak 1 hour

**Comment by romach** [comment]
@vaa25 it will be better to add actual links of documents to the first comment
For example:

> **Additional links:**
> * [Discussion of crowler architecture](https://docs.google.com/document/d/1VUIU-DV1VQls2V6Yt3IrrOMexkalaP1__-8z1r-wLlA/edit);
> * [Example dcument](example.com);

**Comment by vaa25** [comment]
@romach it is the same document

**Comment by romach** [comment]
@vaa25 yes I was wrong. 
But it is better to give descriptive titles to the links (_Discussion of crowler architecture_) and these titles should be the same in all comments.

**Comment by vaa25** [comment]
@romach Purpose of that comment was calling of vkuchin, not link to doc.
