### ISSUE TITLE
Sample html mock

### ISSUE THREAD

**Issue by vaa25** [JuniorsJava/itevents#176]
Create simple html page for sample integration and [mock](http://wiremock.org/java-usage.html) it with [WireMock](http://wiremock.org/). You can inspirate yourself by DOU or any other portal. 
Page must contain: 
* title of event 
* date of event
* time of start event
* address
* registration link
* city name
* describing text

**Comment by vaa25** [comment]
done https://gitlab.com/Juja-ITevents/integrationexample
@AndriyBaibak 4 hours

**Comment by romach** [comment]
@vaa25 last build is [failed](https://gitlab.com/Juja-ITevents/integrationexample/builds)

**Comment by romach** [comment]
@AndriyBaibak 4 hours

**Comment by vaa25** [comment]
@romach fixed

**Comment by romach** [comment]
@vaa25 what is purpose of `Main` class?

**Comment by vaa25** [comment]
@romach to prepare base for further integration development and to show principle of WireMock using

**Comment by romach** [comment]
@vaa25 as I understand we need WireMock only in tests. Am I right?

**Comment by vaa25** [comment]
@romach no. this integration is a sample. In real integration data will be downloaded from web, but here we'll provide data for parsing by WireMock

**Comment by romach** [comment]
@vaa25 OK, but I think that this class must hame more obvious. For example, `SampleIntegration`

**Comment by vaa25** [comment]
@romach [fixed in new branch](https://gitlab.com/Juja-ITevents/integrationexample/commits/%23176)

**Comment by romach** [comment]
@vaa25 **PASSED**
@AndriyBaibak time spent: 10 minutes
