### ISSUE TITLE
Development Infrastructure Openshift

### ISSUE THREAD

**Issue by vkuchyn** [JuniorsJava/itevents#18]
Налаштувати тестове оточення на базі опеншифт - Postgre + Jenkins + Tomcat
Вимоги щодо CI:
1. Наявність білда гілки master автоматично після комітів
2. Наявність білда deploy для мануального деплою апп в тестове середовище
3. Нотифікація розробникам, які завалили збірку
UPD: 
Поточні проблеми:
-  падають тести. 
- невідомо чи налагодився деплой. Раніше через різний формат дат падав при інсерті тестових данних
- Не працює нотифікація - проблеми з SMTP сервером.

**Comment by alex-anakin** [comment]
Added ability of connection to postgres  DB on openshift server

**Comment by vkuchyn** [comment]
[7/14/15, 9:43:57 AM] Viktor Kuchyn: Маємо завалені білди на дженкінз
https://ci-itevents.rhcloud.com/job/ci-build/lastBuild/console
[7/14/15, 9:44:09 AM] Viktor Kuchyn: https://ci-itevents.rhcloud.com/job/webserver-build/27/console
[7/14/15, 9:46:39 AM] Viktor Kuchyn: На цю тему багато статей в гугл
https://www.google.co.th/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=returned+status+code+128%3A+fatal%3A+cannot+copy+%3A+No+such+file+or+directory

**Comment by zccmj** [comment]
@vkuchyn помилка виникає при невдалому конекшені до github, пофіксив баг збільшиви до 3х спроб конекшенів до github.

**Comment by vkuchyn** [comment]
Поточні проблеми:

падають тести.
невідомо чи налагодився деплой. Раніше через різний формат дат падав при інсерті тестових данних
Не працює нотифікація - проблеми з SMTP сервером.

**Comment by alex-anakin** [comment]
Проблема решена с помощью использования локальных свойств.
Описание на вики: https://github.com/JuniorsJava/itevents/wiki/*.properties-rule
