### ISSUE TITLE
Handle situatuation when user try to register with existing username

### ISSUE THREAD

**Issue by romach** [JuniorsJava/itevents#183]
When user try to register with existing username the following error is returned from `/users/register` controller: [link to pastebin.com](http://pastebin.com/9UPDVYPP)

**Comment by IgorMaksymov** [comment]
in addition to this task. i propose remove ` return new ResponseEntity(HttpStatus.IM_USED);` and
`return new ResponseEntity(HttpStatus.CREATED);` and handle this with an exception handler

**Comment by vaa25** [comment]
@romach use pastebin.com for large code, please

**Comment by IgorMaksymov** [comment]
blocked with #155 @AndriyBaibak @alex-anakin pls fix

**Comment by IgorMaksymov** [comment]
@AndriyBaibak time spent: 3h

**Comment by IgorMaksymov** [comment]
@AndriyBaibak time spent: 20m

**Comment by IgorMaksymov** [comment]
@AndriyBaibak time spent: 30m

**Comment by IgorMaksymov** [comment]
@AndriyBaibak time spent 10m
