### ISSUE TITLE
Move EventRestController logic

### ISSUE THREAD

**Issue by vaa25** [JuniorsJava/itevents#186]
Move logic from EventRestController into services and fix old and add new test for this moving

**Comment by IgorMaksymov** [comment]
@vaa25 i dont see any logic there, that should be moved

**Comment by IgorMaksymov** [comment]
@vaa25 tell, what should be moved.

**Comment by IgorMaksymov** [comment]
@AndriyBaibak time spent: 3h

**Comment by IgorMaksymov** [comment]
@AndriyBaibak time spent: 10m

**Comment by IgorMaksymov** [comment]
@AndriyBaibak time spent: 10m

**Comment by IgorMaksymov** [comment]
@AndriyBaibak time spent: 10m
