### ISSUE TITLE
Fix 403 error when enter admin resources (/admin, /users/*/events) with admin user.

### ISSUE THREAD

**Issue by romach** [JuniorsJava/itevents#196]
[Discussion of this bug](https://github.com/JuniorsJava/itevents/pull/144#issuecomment-194480839).

**Comment by IgorMaksymov** [comment]
@roma-ilnitsky @romach this is not because 

> That is why becouse role should name like ROLE_SOME.

something wrong with retrieving role and setting it to UserDetails

**Comment by IgorMaksymov** [comment]
@AndriyBaibak time spent 2h30m
