### ISSUE TITLE
Return JSON error if user hasn't rights

### ISSUE THREAD

**Issue by romach** [JuniorsJava/itevents#197]
JSON error should be returned if user hasn't admin rights (for example if enter `/admin**`, `/users/*/events` as `subscriber`).
This issue was creatd while task #130 execution.

**Comment by roma-ilnitsky** [comment]
Spring Security return
`Status = 401  Error; message = Unauthorized; body = `
After that server (tomcat, jetty) generate own Response Body.
If we wanna get JSON error message into Response Body we have to create own error Handler
@romach do you agree?
@AndriyBaibak: 1:30

**Comment by romach** [comment]
@roma-ilnitsky as I know when user hasn't rights to enter `/admin**`:
* Spring Security generates [`AccessDeniedException`](http://docs.spring.io/spring-security/site/docs/current/apidocs/org/springframework/security/access/AccessDeniedException.html);
* using [`ExceptionTranslationFilter`](http://docs.spring.io/spring-security/site/docs/current/apidocs/org/springframework/security/web/access/ExceptionTranslationFilter.html) it delegates this exception to [`AccessDeniedHandlerImpl`](http://docs.spring.io/spring-security/site/docs/current/apidocs/org/springframework/security/web/access/AccessDeniedHandlerImpl.html).
* so, we need to create custom `AccessDeniedHandler`;

**Comment by roma-ilnitsky** [comment]
@romach I change RestAuthenticationEntryPoint it's work fine )
