### ISSUE TITLE
refactor exceptions

### ISSUE THREAD

**Issue by IgorMaksymov** [JuniorsJava/itevents#207]
remove antipatterns, described here from our exceptions.
https://community.oracle.com/docs/DOC-983543

**Comment by IgorMaksymov** [comment]
@alex-anakin please, leave your opinion on this task.
1) do we really need this
2) is description is OK
3) how we need to do this.

**Comment by alex-anakin** [comment]
1. The purpose is not clear
2. Nope.
3. You can resolve issue #168 instead.
