### ISSUE TITLE
add logging system

### ISSUE THREAD

**Issue by alex-anakin** [JuniorsJava/itevents#21]
Prefer Log4j or Slf4j logging system.
It's necessary to describe how to change seetings of logging in project wiki.

**Comment by evgenijboldyr** [comment]
Хочу уточнить куда мы будем логировать действия кроме консоли?

**Comment by alex-anakin** [comment]
файл на жестком диске для заданных уровней, консоль обязательно для заданных уровней, на какое-то мыло (вынеси в отдельный файл настройки) - только для уровня ERROR

заданные уровни - ДЕБАГ и выше

**Comment by evgenijboldyr** [comment]
Хочу еще уточнить по поводу правил именования файлов? В локальном репозитарии log4j заработал. В консоль инфа выводится.
