### ISSUE TITLE
Fix pmd in crawler

### ISSUE THREAD

**Issue by vaa25** [JuniorsJava/itevents#214]
Fix launch gradle pmd plugin. The exception is:
`[ant:pmd] net.sourceforge.pmd.RuleSetNotFoundException: Can't find resource 'rulesets/java-strings.xml' for rule 'null'.  Make sure the resource is a valid file or UR
L and is on the CLASSPATH. Here's the current classpath: D:\gradle-2.4\bin\..\lib\gradle-launcher-2.4.jar`

**Comment by romach** [comment]
@AndriyBaibak spent 2 hours

**Comment by vaa25** [comment]
@AndriyBaibak issue is merged. close please. 4hours
