### ISSUE TITLE
Configure Github Pull Request builder plugin

### ISSUE THREAD

**Issue by vkuchyn** [JuniorsJava/itevents#37]
Необхідно налаштувати плагін під Jenkins який збирає Pull-requests і відхиляє їх, якщо ті неуспішно зібрались
https://wiki.jenkins-ci.org/display/JENKINS/GitHub+pull+request+builder+plugin

**Comment by zccmj** [comment]
Тестовий коментарій із jenkins

**Comment by zccmj** [comment]
Плагін чомусь неспрацьовує при новому пул реквесті
