### ISSUE TITLE
subscriber_weekly_digest 

### ISSUE THREAD

**Issue by vkuchyn** [JuniorsJava/itevents#47]
Як Subscriber я хочу отримувати щотижня лист з дайджестом нових подій за фільтром на наступний тиждень.

Це базова фіча, пропоную розбити на підзадачі, оскільки вона дуже об'ємна

1. Необхідно реалізувати DAO, Service методи вибору подій на наступний тиждень згідно рейтингу і зазначеного підпищиком фільтру. Рейтинг базується на основі інтересу до події - кількості переходів на сторінку-оригінал

2. На основі готового шаблону зверстати лист, підставивши події. Шаблони можно реалізувати на основі XSLT-перетворенні. 

3. Надіслати сформований лист клієнту за допомогою сервісу https://sendgrid.com/docs/API_Reference/Web_API_v3/index.html

4. Регулярно за розкладом надсилати пошту всім підпищикам.

***

**Текущие проблемы**:

**Comment by zavodnyuk** [comment]
Берем с @zccmj  3 и 4 сабтаск

**Comment by Antonerof** [comment]
Скорее всего возьмем с https://github.com/romach 1 и 2 сабтаски.

**Comment by zccmj** [comment]
@vkuchyn як часто треба відсилати листи користувачам, раз на добу ?

**Comment by Antonerof** [comment]
@vkuchyn как будем считать переходы по внешней ссылке ивента? На стороне клиента будет ссылка типа http://host/itevents?goto="link to event"

**Comment by vaa25** [comment]
Все уже подсчитано до вас в visit_log

**Comment by Antonerof** [comment]
Вот оно че. Ясно, спасибо.

**Comment by alex-anakin** [comment]
Замечания здесь: https://docs.google.com/document/d/1fM33O_uZm-JSh-64aZgi6E8zfDU3NqJVMVVKF5Ap3yI/edit?usp=sharing

**Comment by vaa25** [comment]
проверьте версию подключаемых вами модулей спринга
