### ISSUE TITLE
Активація підписки.

### ISSUE THREAD

**Issue by vkuchyn** [JuniorsJava/itevents#48]
Після того, як користувач залишив свої персональні дані і налаштунки, необхідно надіслати лист для підтвердження активації з OTP (One time password). Виглядатиме наступним чином - http://host.com/itevents/...../sdnJHsdfo8usdn38h3r87
sdnJHsdfo8usdn38h3r87 - otp який генерується програмою. Якщо користувач перейшов за цим лінком, профіль користувача необхідно активувати (неактивні підпищики не отримують розсилку). 
Задати для OTP цикл життя який налаштовується з конфігу. Напр, якщо термін придатності 1 день, то лінк не діятиме, якщо користувач перейшов за ним через день і більше
Для генерації тексту листа використовувати сервіс на основі XSLT перетворень із задачі #47
Для надсилання листів використовувати сервіс із задачі #47. 
Якщо такі ще не реалізовані - використовувати стаби. (прості реалізації інтерфейсів відповідних сервісів)

**Comment by IgorMaksymov** [comment]
blocked with #155 @AndriyBaibak

**Comment by IgorMaksymov** [comment]
blocked with #156 @AndriyBaibak
