### ISSUE TITLE
Отримування нагадувань

### ISSUE THREAD

**Issue by vkuchyn** [JuniorsJava/itevents#53]
Реалізувати сервіс, який запускається з певною періодикою і надсилає всім підпищикам, які натиснули "Я піду" нотифікації з нагадуванням про подію. Нагадувати необхідно за день. Втім, цей параметр винести в конфіги. 
Для надсилання листів використовувати сервіс із задачі #47

**Comment by zavodnyuk** [comment]
@vkuchyn уточняющий вопрос: Для этого сервиса нужен отдельный шедулер или добавить расписание в тот что уже есть (из issue47)?
