### ISSUE TITLE
subscriber_weekly_digest DAO, Servic рівень

### ISSUE THREAD

**Issue by roma-ilnitsky** [JuniorsJava/itevents#63]
Підзадача #47 таску.

Необхідно реалізувати DAO, Service методи вибору подій на наступний тиждень згідно рейтингу і зазначеного підпищиком фільтру. Рейтинг базується на основі інтересу до події - кількості переходів на сторінку-оригінал

**Comment by Antonerof** [comment]
С @romach берем на себя.

**Comment by romach** [comment]
**Текущее проблемы:**
* [ ] не работает тест `org.itevents.service.RatingServiceTest > testChooseMostPopularEventsForUser`
* [ ] не работает тест `org.itevents.mybatis.mapper.util.SQLBuilderTest > testBuildingFilteredEventsQuery`
* [ ] не работает dbUnit (закомментированные строки 9-12 в файле `testApplicationContext.xml`)

**Comment by IgorMaksymov** [comment]
@roma-ilnitsky @Antonerof @romach @vkuchyn @AndriyBaibak this task is open or not?

**Comment by vkuchyn** [comment]
@roma-ilnitsky What is the status? PR closed long time ago. Task is still in progress - please, verify it
