### ISSUE TITLE
XSLT-перетворення

### ISSUE THREAD

**Issue by roma-ilnitsky** [JuniorsJava/itevents#64]
Підзадача #47 таску.

На основі готового шаблону зверстати лист, підставивши події. Шаблони можно реалізувати на основі XSLT-перетворенні.

**Comment by Antonerof** [comment]
С @romach берем на себя.

**Comment by romach** [comment]
@vkuchyn [демо](https://www.youtube.com/watch?v=WkYNo1D8u-M&feature=youtu.be)
